### ISSUE TITLE
Feature: osOptions and hmOptions as module inputs

### ISSUE THREAD

**Issue by Noah765** [FlafyDev/combined-manager#5]
Being able to easily access the NixOS / home manager options would be very handy when defining custom options, as it allows you to reuse existing option definitions.
For example, this is part of my home manager module for impermanence that I would like to move to combined manager:
```nix
{
  lib,
  options,
  ...
}:
with lib;
{
  options.impermanence =
    let
      persistenceOptions = options.home.persistence.type.getSubOptions [ ];
    in
    {
      enable = mkEnableOption "impermanence";
      directories = persistenceOptions.directories;
      files = persistenceOptions.files;
    };
}
```
Note that the `home.persistence.directories' and `home.persistence.files' options are non-trivial, so this avoids a lot of repetition and results in a cleaner configuration.

Adding these options via an `osOptions` and `hmOptions` module entry would mean that I could trivially move this to the combined manager.

By the way, thanks for your great work!

**Comment by Noah765** [comment]
I am currently working on a fork that provides this feature, and will create a PR to see if you want to merge with the fork.

**Comment by FlafyDev** [comment]
Hey, sorry for not commenting sooner, I don't have much time to work on this project rn.

And thanks for wanting to PR! You can keep the issue open until it's fixed on main if you want.
